INSERT INTO Generos (id, nombre) VALUES (1, 'Acción');
INSERT INTO Generos (id, nombre) VALUES (2, 'Aventura');
INSERT INTO Generos (id, nombre) VALUES (3, 'Comedia');
INSERT INTO Generos (id, nombre) VALUES (4, 'Drama');
INSERT INTO Generos (id, nombre) VALUES (5, 'Fantasía');
INSERT INTO Generos (id, nombre) VALUES (6, 'Ciencia ficción');
INSERT INTO Generos (id, nombre) VALUES (7, 'Musical');
INSERT INTO Generos (id, nombre) VALUES (8, 'Romance');
INSERT INTO Generos (id, nombre) VALUES (9, 'Suspenso');
INSERT INTO Generos (id, nombre) VALUES (10, 'Terror');
INSERT INTO Generos (id, nombre) VALUES (11, 'Animación');
INSERT INTO Generos (id, nombre) VALUES (12, 'Documental');
INSERT INTO Generos (id, nombre) VALUES (13, 'Bélico');
INSERT INTO Generos (id, nombre) VALUES (14, 'Western');
INSERT INTO Generos (id, nombre) VALUES (15, 'Histórico');
INSERT INTO Generos (id, nombre) VALUES (16, 'Policiaco');
INSERT INTO Generos (id, nombre) VALUES (17, 'Thriller');
INSERT INTO Generos (id, nombre) VALUES (18, 'Guerra');
INSERT INTO Generos (id, nombre) VALUES (19, 'Misterio');
INSERT INTO Generos (id, nombre) VALUES (20, 'Familiar');
INSERT INTO Generos (id, nombre) VALUES (21, 'Crimen');
INSERT INTO Generos (id, nombre) VALUES (22, 'Familia');
INSERT INTO Generos (id, nombre) VALUES (23, 'Infantil');
INSERT INTO Generos (id, nombre) VALUES (24, 'Realidad');
INSERT INTO Generos (id, nombre) VALUES (25, 'Independiente');
INSERT INTO Generos (id, nombre) VALUES (26, 'Noir');
INSERT INTO Generos (id, nombre) VALUES (27, 'Adultos');
INSERT INTO Generos (id, nombre) VALUES (28, 'Deporte');
INSERT INTO Generos (id, nombre) VALUES (29, 'Musical');
INSERT INTO Generos (id, nombre) VALUES (30, 'Artes Marciales');
INSERT INTO Generos (id, nombre) VALUES (31, 'Historia');
INSERT INTO Generos (id, nombre) VALUES (32, 'Filosofía');
INSERT INTO Generos (id, nombre) VALUES (33, 'Psicológico');
INSERT INTO Generos (id, nombre) VALUES (34, 'Conspiración');
INSERT INTO Generos (id, nombre) VALUES (35, 'Superhéroes');
INSERT INTO Generos (id, nombre) VALUES (36, 'Cine independiente');
